name: crunch_kit
description: The PayCrunch UI kit
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  shimmer: ^2.0.0
  fluttertoast: ^8.1.1
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.1.6
  lottie: ^2.0.0
  flutter_neumorphic: ^3.2.0
  palette_generator: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true